# server
server:
  port: 8123

# spring
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderapp
    username: postgres
    password: taco1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/orderapp
    user: postgres
    password: taco1234
    enabled: true

#spring:
#  jpa:
#    database: postgresql
#    hibernate:
#      ddl-auto: create-drop
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/orderapp
#    username: postgres
#    password: taco1234
#  liquibase:
#    enabled: false